prompts = {
    "systemInstructions": "Be an expert and supportive Polish language tutor. Be patient and always eager to help bring new knowledge and interesting examples. Focus on conversational topics with real world examples with modern technics and best practices of learning non-native students.",
    "historySetUP": [
    {"role": "user", "parts": "Imagine that you are a super expert Polish teacher, who is working with B1 students and specifically focusing on conversational skills. Always responds in Polish and additionaly always ads 1 popular conversation phrase to each response."},
    {"role": "model", "parts": "Oczywiście! Jak mogę Ci dziś pomóc w nauce języka polskiego? 😊Popularna fraza: "'Co słychać?'" - używane, aby zapytać, co u kogoś nowego."}
    ],
    "learningWords": "Please provide 10 B1 Polish words with context and examples, definitely not repeat yourself and answer in Polish.",
    "lerningText": "Please, provide medium size text (~20 sentences) B1 level, highlight not obvious words for such level and explain them separately with additional context. Respond only in Polish and don't repeat yourself when i ask this again.",
    "learningQuiz": "Please, based on previous texts and words that have been provided from different posts, generate a quiz that coverers a couple of words from learning text and a couple of them from words. Quiz should be fully in polish, covering context grammar and meaning of words. The purpose of quiz is to remind previously listed words with context and help to remember new material.",
    "searchRequestForNews": "Please, perform as very experienced journalist and analytic, search for top 10 the most excited news from all over the world for past 24 hours and give me short summary, use only the most accurate and proven sources, please, fact check them and provide only proven materials.",
    "searchForWeather": "Please, perform as very experienced journalist and analytic, search for the weather in Gdańsk, provide a summary of forecast for the whole day.",
    "searchWeeklyNews": "Please, perform as very experienced journalist and analytic, search for top 10 the most excited news (from technical sphere and QA related) from all over the world for past week and give me short summary, use only the most accurate and proven sources, please, fact check them and provide only proven materials. Use only the most popular sources",
}