prompts = {
    "historySetUP": [
        {"role": "user", "parts": [{"text": "Imagine that you are a super expert Polish teacher, who is working with B1 students and specifically focusing on conversational skills. Always responds in Polish and additionaly always ads 1 popular conversation phrase to each response."}]},
        {"role": "model", "parts": [{"text": "Oczywiście! Jak mogę Ci dziś pomóc w nauce języka polskiego? 😊Popularna fraza: 'Co słychać?' - używane, aby zapytać, co u kogoś nowego."}]}
    ],
    "learningWords": "Proszę, podaj 10 polskich słów na poziomie B1, które są związane z tematem 'podróżowanie i wakacje'. Dla każdego słowa podaj jego definicję oraz praktyczne zdanie przykładowe. Upewnij się, że słowa są zróżnicowane (np. rzeczowniki, czasowniki, przymiotniki). Format odpowiedzi powinien wyglądać następująco: 'Słowo - Definicja. Przykład: [zdanie]'. Cała odpowiedź musi być w języku polskim. Please, do not repeat words from previous posts. All new words have to be new and do not use words from previous messages. You have to respond only with 4096 characters maximum.",
    "lerningText": "НNapisz krótki dialog lub sytuację na poziomie B1 na różne tematy, nie powinny się powtarzać (np. w sklepie/kawiarni/szpitalu). Każda z Twoich wiadomości to jedna sytuacja. Dialog powinien zawierać nowe słownictwo, a jeśli coś jest skomplikowane, wyjaśnienie słów. Proszę pisać wyłącznie po polsku. Text have to be always unique and with new different lexica/new words. Don't repeat lexica from previous texts. Always new topic, please. You have to respond only with 4096 characters maximum.",
    "learningQuiz": "Na podstawie słów i tekstów z naszej dotychczasowej konwersacji, stwórz krótki quiz składający się z 10 pytań. Quiz ma na celu sprawdzenie znajomości słownictwa i gramatyki na poziomie B1. Proszę o zróżnicowane typy pytań: 1-2 pytania typu 'uzupełnij lukę w zdaniu', 1-2 pytania wielokrotnego wyboru (A, B, C) dotyczące znaczenia słowa, oraz 1 pytanie otwarte, gdzie muszę samodzielnie zbudować zdanie z podanym słowem. Na końcu, w osobnej, wyraźnie oznaczonej sekcji 'Klucz odpowiedzi', podaj prawidłowe odpowiedzi. You have to respond only with 4096 characters maximum.",
    "searchRequestForNews": "As a very experienced journalist and analytic, please search the internet using your available tools for the top 10 most significant and breaking news stories from all over the world within the past 24 hours. Focus exclusively on the most accurate and proven sources, ensuring all information is rigorously fact-checked and only proven materials are included in your summary. Provide a concise summary of each story. Your response must not exceed 4096 characters. Cała odpowiedź musi być w języku polskim.",
    "searchForWeather": "Using your search tool, find the weather forecast for Gdańsk, Poland for today. Act as a clear and concise weather reporter. Provide a summary that includes: temperature throughout the day (morning, afternoon, evening), 'feels like' temperature (temperatura odczuwalna), chance of precipitation as a percentage, wind speed and direction, and the expected conditions (e.g., sunny, partly cloudy, rain showers). You have to respond only with 4096 characters maximum. Cała odpowiedź musi być w języku polskim.",
    "searchWeeklyNews": "Act as a tech industry analyst. Use your search tool to find the 5 most significant news stories and developments in the 'software development and quality assurance (QA)' sector from the past week. For each story, provide: 1. A clear headline. 2. The primary source (e.g., TechCrunch, a specific company's blog, etc.). 3. A 2-3 sentence summary explaining the news and its potential impact on the industry. Focus on reputable, well-known tech news outlets and primary sources. You have to respond only with 4096 characters maximum. Cała odpowiedź musi być w języku polskim.",
    "wordsReminders": "Stwórzmy szybką powtórkę. Wybierz 10 słów lub zwrotów z naszych poprzednich lekcji (ale nie z ostatniej). Przedstaw je jako quiz w formie 'definicja -> słowo'. Podaj tylko definicje w formie ponumerowanej listy, abym mógł/mogła spróbować odgadnąć każde słowo. Na samym dole odpowiedzi, po wyraźnym oddzieleniu (np. linią '---'), stwórz sekcję 'Odpowiedzi' i podaj prawidłowe słowa pasujące do każdej definicji. You have to respond only with 4096 characters maximum. Cała odpowiedź musi być w języku polskim."
}